### ISSUE TITLE
Check for latest Ruby version in a GitHub Action

### ISSUE THREAD

**Issue by joshrowley** [joshrowley/summit#13]
## Summary

I want to keep this project on the latest versions of Ruby (and other dependencies as much as possible). Add a GitHub job that will fail if there's a newer version of Ruby.

## Proposed Solution

You can create a GitHub Action that:

1. Detects the Ruby version used in your repo (e.g., from .ruby-version or Gemfile).
2. Fetches the latest stable Ruby version from the official source.
3. Compares the two and fails the workflow if they don’t match.

Here’s a complete example workflow:

```yaml
# .github/workflows/check-latest-ruby.yml
name: Check Latest Ruby Version

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check-ruby-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Ruby version from .ruby-version
        id: local_version
        run: echo "version=$(cat .ruby-version)" >> $GITHUB_OUTPUT

      - name: Fetch latest stable Ruby version
        id: latest_version
        run: |
          latest=$(curl -s https://raw.githubusercontent.com/postmodern/ruby-versions/master/ruby/stable.txt | head -n 1)
          echo "version=$latest" >> $GITHUB_OUTPUT

      - name: Compare versions
        run: |
          echo "Local Ruby: ${{ steps.local_version.outputs.version }}"
          echo "Latest Ruby: ${{ steps.latest_version.outputs.version }}"
          if [ "${{ steps.local_version.outputs.version }}" != "${{ steps.latest_version.outputs.version }}" ]; then
            echo "Error: Ruby version is not up to date."
            exit 1
          fi
```

**How It Works**:

• `cat .ruby-version` grabs your project’s Ruby version.
• The latest stable Ruby version is fetched from [postmodern/ruby-versions](https://github.com/postmodern/ruby-versions).
• It compares both values and fails the job if they differ.
