### ISSUE TITLE
⚡ Speed up GitHub Test Job by Caching Dependencies

### ISSUE THREAD

**Issue by joshrowley** [joshrowley/summit#21]
## Summary

The GitHub Actions test job for Summit installs Ruby gems and JavaScript dependencies on every run, which slows down CI. We should enable caching to significantly improve performance on repeated builds.

## ✅ Goals

- Cache bundle install results to speed up Ruby dependency installation
- Cache yarn install (or npm install) results to speed up JS dependency installation
- Ensure caches are invalidated only when dependencies actually change

## 🧱 Tasks

- [ ] Add actions/cache step to cache vendor/bundle based on Gemfile.lock
- [ ] Add actions/cache step to cache node_modules based on yarn.lock
- [ ] Ensure CI works for both fresh and cached installs
- [ ] Confirm that a bundle install and yarn install are still run (to validate integrity)

## 🛠️ Example Implementation (Ruby + Yarn):

```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true # Automatically handles bundler + cache

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.cache/yarn
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Install JS dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: bin/rails test
```

## 📈 Expected Result:

CI build times should improve by ~30–60% on repeated runs, especially on PRs where dependencies don’t change.
